server:
  port: 9090
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048
# Internationalization
spring.messages.basename: messages/messages
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/  
spring:
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          gateway-neocar-client:
            provider: keycloak
            client-id: gateway-neocar-client
            client-secret: oZXXHad9MqG62iU2JidpyOIyIIXcpcAh
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
app:
  config:
    keycloak:
      url: http://localhost:8080/auth
      realm: spring-test       