eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9191/realms/spring-test
          jwk-set-uri: http://localhost:9191/realms/spring-test/.well-known/openid-configuration

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
